# Starter SConstruct for enscons

import enscons
import pytoml
#from runtime_builder.builder import build_all_items_for_package

metadata = dict(pytoml.load(open("pyproject.toml")))["project"]

full_tag = "py3-none-any"  # pure Python packages compatible with 2+3

env = Environment(
    tools=["default", "packaging", enscons.generate],
    PACKAGE_METADATA=metadata,
    WHEEL_TAG=full_tag,
    ROOT_IS_PURELIB=full_tag.endswith("-any"),
)

py_source = ["chialisp_builder.py"]

other_source = (
    "proj/foo", "proj/program.clsp", "proj/bar.txt"
)

wheel_contents = py_source

source = env.Whl("purelib", wheel_contents, root="")
whl = env.WhlFile(source=source)

sdist_source = (
    File(["PKG-INFO", "README.md", "SConstruct", "pyproject.toml"]) + py_source
)
sdist = env.SDist(source=sdist_source)
env.NoClean(sdist)
env.Alias("sdist", sdist)

# needed for pep517 (enscons.api) to work
env.Default(whl, sdist)
